FROM ubuntu

RUN apt-get update -y && apt-get upgrade -y

RUN DEBIAN_FRONTEND="noninteractive" apt-get install curl vim apt-transport-https wget -y

RUN useradd -ms /bin/bash grafana
USER grafana
WORKDIR /home/grafana

COPY sample-datasource.json /home/grafana/
COPY sample-dashboard.json /home/grafana/
COPY startup.sh /home/grafana/

USER root
RUN chown grafana /home/grafana/sample-datasource.json
RUN chgrp grafana /home/grafana/sample-datasource.json

RUN chown grafana /home/grafana/sample-dashboard.json
RUN chgrp grafana /home/grafana/sample-dashboard.json

RUN chown grafana /home/grafana/startup.sh
RUN chgrp grafana /home/grafana/startup.sh
RUN chmod +x /home/grafana/startup.sh

USER grafana

RUN wget https://dl.grafana.com/oss/release/grafana-8.0.6.linux-amd64.tar.gz
RUN tar -xzf grafana-8.0.6.linux-amd64.tar.gz
RUN rm grafana-8.0.6.linux-amd64.tar.gz

EXPOSE 3000

CMD ["./startup.sh"]