apiVersion: v1
kind: Service
metadata:
        name: elasticsearch
spec:
        ports:
                - protocol: TCP
                  port: 9200
                  targetPort: 9200
        type: ClusterIP
        selector:
                app: elasticsearch
