apiVersion: v1
kind: Service
metadata:
        name: grafana-service
spec:
        ports:
                - protocol: TCP
                  port: 3000
                  targetPort: 3000
        type: LoadBalancer
        selector:
                app: grafana
