apiVersion: apps/v1
kind: Deployment
metadata:
        name: grafana-deployment
        labels:
                app: grafana
spec:
        template:
                metadata:
                        name: grafana-deployment
                        labels:
                                app: grafana
                spec:
                        containers:
                                - name: grafana
                                  image: plaulkar/elasticsearch_logstash_grafana:grafana
        selector:
                matchLabels:
                        app: grafana
