FROM ubuntu

RUN apt-get update -y && apt-get upgrade -y

RUN DEBIAN_FRONTEND="noninteractive" apt-get install curl openjdk-8-jdk vim apt-transport-https wget libdigest-sha-perl python3 -y

RUN useradd -ms /bin/bash ls
USER ls
WORKDIR /home/ls

RUN mkdir data-generation-queries
RUN mkdir data
RUN mkdir data/old
COPY sample-code.py data-generation-queries/
COPY sample-data.conf /etc/logstash/conf.d/
COPY startup.sh /home/ls/

USER root
RUN chown ls /home/ls/data-generation-queries/sample-code.py
RUN chgrp ls /home/ls/data-generation-queries/sample-code.py

RUN chown ls /home/ls/startup.sh
RUN chgrp ls /home/ls/startup.sh
RUN chmod +x /home/ls/startup.sh

USER ls

RUN wget https://artifacts.elastic.co/downloads/logstash/logstash-7.13.3-linux-x86_64.tar.gz
RUN wget https://artifacts.elastic.co/downloads/logstash/logstash-7.13.3-linux-x86_64.tar.gz.sha512
RUN shasum -a 512 -c logstash-7.13.3-linux-x86_64.tar.gz.sha512
RUN tar -xzf logstash-7.13.3-linux-x86_64.tar.gz
RUN rm logstash-7.13.3-linux-x86_64.tar.gz

CMD ["./startup.sh"]